version: "2"

services:
    gitcat:
        container_name: gitcat
        build:
          context: ./
          dockerfile: Dockerfile.dev
        ports:
            - 8888:80
        env_file:
            - config.env
        volumes:
            - ./gitcat.go:/home/gitcat.go
            - ./webapp/:/home/webapp/
