version: "2"

services:
    gitcat:
        container_name: gitcat
        build: ./
        ports:
            - 8080:80
        env_file:
            - config.env
        volumes:
            - ./:/home/