version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.11
  environment:
    - CONTAINER: 'surycat/gitcat'

docker-login: &docker-login
  run:
    name: Docker login
    command: docker login -u $DOCKER_USER -p $DOCKER_PASS

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *docker-login
      - run:
          name: Build image
          command: docker build -t $CONTAINER:head .
      - run:
          name: Push image tags
          command: |
            docker push $CONTAINER:head
            docker tag $CONTAINER:head $CONTAINER:latest
            docker push $CONTAINER:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: docker-creds
          filters:
            branches:
              only: master
